# Этап сборки приложения
FROM golang:1.21.4-alpine3.18 as builder
WORKDIR /source
COPY . .
RUN go build -o /client main.go

# Этап подготовки и запуска
FROM alpine:3.18.2
WORKDIR /app
COPY --from=builder /client /app/client
ENTRYPOINT ["/app/client"]
